version: "2"

services:
  cachet:
    external_links:
  -   ${postgres_link}:postgres
    image: cachethq/docker:latest
    environment:
      - "DB_DRIVER=pgsql"
      - "DB_HOST=postgres"
      - "DB_DATABASE=postgres"
      - "DB_USERNAME=${POSTGRES_USER}"
      - "DB_PASSWORD=${POSTGRES_PASSWORD}"
      - "APP_KEY=${APP_KEY}"
    links: 
      - postgres:postgres
    depends_on: 
      - postgres