pydio:
  image: cl3m3nt/pydio-docker:v0.1
  ports:
    - 443:443
    - 80:80
  links:
    - pydiodb
  volumes:
    - "${linkfile}:/var/www/pydio-core/data/files/"
    - "${linkpersonal}:/var/www/pydio-core/data/personal/"
pydiodb:
  image: mariadb:10.0.27
  environment:
    MYSQL_ROOT_PASSWORD: "${rootpass}"
    MYSQL_USER: "${user}"
    MYSQL_PASSWORD: "${userpass}"
    MYSQL_DATABASE: "${dbname}"
