.catalog:
  name: "Pydio"
  version: "v1"
  description: "Pydio for Secure File Sharing for business"
  minimum_rancher_version: v0.46.0
  questions:
    - variable: "linkfile"
      type: string
      required: true
      label: "Link volume"
      description: "volumes for /var/www/pydio-core/data/files/"
    - variable: "linkpersonal"
      type: string
      required: true
      label: "Link volume"
      description: "volumes for /var/www/pydio-core/data/personal/"
    - variable: "rootpass"
      type: string
      required: true
      label: "root password for database"
      description: "root password for database"
    - variable: "user"
      type: string
      required: true
      label: "userpass"
      description: "user for database"
    - variable: "userpass"
      type: string
      required: true
      label: "root password for database"
      description: "root password for database"
    - variable: "dbname"
      type: string
      required: true
      label: "name for database"
      description: "name for database"
