.catalog:
  name: Logspout
  version: 0.2.0-rancher1
  description: |
    Logspout is a log router for Docker containers.
  questions:
    - variable: "route_uri"
      label: "Logspout route for logs"
      type: "string"
      required: true
      default: "logstash://logstash:5000"
      description: |
        This will be the target where all logs are sent. 
        By default it uses logstash and points to a linked service
        logstash.
    - variable: "target_link"
      label: "Logging Target Link"
      type: "service"
      required: true
      default: "logstash/logstash"
      description: |
        Name of the stack/service to send logs to.
    - variable: "target_link_name"
      label: "Link Name"
      type: "string"
      required: true
      default: "logstash"
      description: |
        Alias link name
      description: |
        DNS name to send logs to. The DNS
        Name should line up with the route uri.
