name: Nginx Proxy # Name of the Catalog Entry
description: |
  An Nginx proxy secured with Letsencrypt
version: v1 # Version of the Catalog to be used
category: Applications # Category to be used for searching catalog entries
maintainer: Ruslan Ayupov <https://github.com/RuslanAyupov # The maintainer of the catalog entry
license: The MIT License # The license
projectURL: https://git.development-lab.site # A URL related to the catalog entry