---
version: '2'
services:
  nextcloud:
    restart: always
    image: sameersbn/nextcloud:latest
    command: app:nextcloud
    environment:
    - DEBUG=false
    - TZ=Europe/Moscow
    - DB_TYPE=pgsql
    - DB_HOST="${posgresql_hostname}"
    - DB_USER=dba
    - DB_PASS=steelpad
    - DB_NAME=nextcloud

    - NEXTCLOUD_URL=http://${nextcloud_hostname}

    - NEXTCLOUD_ADMIN_USER=admin
    - NEXTCLOUD_ADMIN_PASSWORD=passw0rd

    - NEXTCLOUD_UPLOAD_MAX_FILESIZE=4G
    - NEXTCLOUD_MAX_FILE_UPLOADS=20

    - NEXTCLOUD_BACKUPS_EXPIRY=0

    volumes:
    - /opt/shared-resources/nextcloud:/var/lib/nextcloud

  nginx:
    restart: always
    image: sameersbn/nextcloud:latest
    command: app:nginx
    labels:
      rap.host: "${nextcloud_hostname}"
      rap.port: 80
      rap.proto: http
      rap.le_host: "${nextcloud_hostname}"
      rap.le_email: "divo@divo.net.pl"
    environment:
    - NEXTCLOUD_PHP_FPM_HOST=nextcloud
    - NEXTCLOUD_PHP_FPM_PORT=9000
    depends_on:
    - nextcloud