---
version: '2'
services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    environment:
    - DB_USER=nextcloud
    - DB_PASS=password
    - DB_NAME=nextcloud
    volumes:
    - /data/nextcloud/postgresql:/var/lib/postgresql

  nextcloud:
    restart: always
    image: sameersbn/nextcloud:11.0.1
    command: app:nextcloud
    environment:
    - DEBUG=false
    - TZ=Europe/Warsaw

    - DB_TYPE=pgsql
    - DB_HOST=postgresql
    - DB_USER=nextcloud
    - DB_PASS=password
    - DB_NAME=nextcloud

    - NEXTCLOUD_URL=http://${nextcloud_hostname}

    - NEXTCLOUD_ADMIN_USER=admin
    - NEXTCLOUD_ADMIN_PASSWORD=admin

    - NEXTCLOUD_UPLOAD_MAX_FILESIZE=4G
    - NEXTCLOUD_MAX_FILE_UPLOADS=20

    - NEXTCLOUD_BACKUPS_EXPIRY=0
    depends_on:
    - postgresql
    volumes:
    - /data/nextcloud/data:/var/lib/nextcloud

  nginx:
    restart: always
    image: sameersbn/nextcloud:11.0.1
    command: app:nginx
    labels:
      rap.host: "${nextcloud_hostname}"
      rap.port: 80
      rap.proto: http
      rap.le_host: "${nextcloud_hostname}"
      rap.le_email: "divo@divo.net.pl"
    environment:
    - NEXTCLOUD_PHP_FPM_HOST=nextcloud
    - NEXTCLOUD_PHP_FPM_PORT=9000
    depends_on:
    - nextcloud